// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfkbkhkplppdbolffahs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpma2JraGtwbHBwZGJvbGZmYWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTUxNzIsImV4cCI6MjA2MjUzMTE3Mn0.FrNrzndIpSF_3ZvDMPKZiRe83BqWzpoF1Os0yk1xpSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);